package classify

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const SchemaVersion = 2

const (
	StatePending = "pending"
	StateSuccess = "success"
	StateFailed  = "failed"
	StateSkipped = "skipped"
)

var ErrFFmpegUnavailable = errors.New("ffmpeg unavailable")

// Detection is a normalized detection entry for people/animals.
type Detection struct {
	Category   string  `json:"category"`
	Label      string  `json:"label"`
	Confidence float64 `json:"confidence"`
}

// Sidecar is persisted as <video>.detections.json.
type Sidecar struct {
	SchemaVersion   int         `json:"schema_version"`
	RelativePath    string      `json:"relative_path"`
	FileSize        int64       `json:"file_size"`
	FileModTime     string      `json:"file_mod_time"`
	State           string      `json:"state"`
	Provider        string      `json:"provider"`
	Model           string      `json:"model"`
	Attempts        int         `json:"attempts"`
	UpdatedAt       string      `json:"updated_at"`
	LastError       string      `json:"last_error,omitempty"`
	Detections      []Detection `json:"detections,omitempty"`
	HasPerson       bool        `json:"has_person"`
	HasAnimal       bool        `json:"has_animal"`
	HasVehicle      bool        `json:"has_vehicle"`
	ThumbnailPath   string      `json:"thumbnail_path,omitempty"`
	MQTTPublishedAt string      `json:"mqtt_published_at,omitempty"`
	MQTTLastError   string      `json:"mqtt_last_error,omitempty"`
	RawResponse     string      `json:"raw_response,omitempty"`
}

func sidecarPath(videoPath string) string {
	return videoPath + ".detections.json"
}

// LoadSidecar reads the sidecar for a video path.
func LoadSidecar(videoPath string) (*Sidecar, error) {
	payload, err := os.ReadFile(sidecarPath(videoPath))
	if err != nil {
		return nil, err
	}
	var out Sidecar
	if err := json.Unmarshal(payload, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// WriteSidecar atomically writes sidecar metadata for a video path.
func WriteSidecar(videoPath string, s Sidecar) error {
	dir := filepath.Dir(videoPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".detections-*.json")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	enc := json.NewEncoder(tmp)
	enc.SetIndent("", "  ")
	if err := enc.Encode(s); err != nil {
		_ = tmp.Close()
		_ = os.Remove(tmpPath)
		return err
	}
	if err := tmp.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	if err := os.Rename(tmpPath, sidecarPath(videoPath)); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	return nil
}

func sidecarForVideo(storageRoot, videoPath, provider, model string) Sidecar {
	rel, _ := filepath.Rel(storageRoot, videoPath)
	info, _ := os.Stat(videoPath)
	out := Sidecar{
		SchemaVersion: SchemaVersion,
		RelativePath:  filepath.ToSlash(rel),
		Provider:      provider,
		Model:         model,
		UpdatedAt:     time.Now().UTC().Format(time.RFC3339),
	}
	if info != nil {
		out.FileSize = info.Size()
		out.FileModTime = info.ModTime().UTC().Format(time.RFC3339)
	}
	return out
}

// IsVideoPath returns true when file extension is a known video type.
func IsVideoPath(path string) bool {
	ext := strings.ToLower(filepath.Ext(path))
	switch ext {
	case ".mp4", ".m4v", ".mov", ".avi", ".mkv", ".webm", ".mpg", ".mpeg", ".3gp", ".wmv", ".ts":
		return true
	default:
		return false
	}
}

// IsDetectionSidecarPath identifies sidecar files generated by classifier.
func IsDetectionSidecarPath(path string) bool {
	return strings.HasSuffix(strings.ToLower(path), ".detections.json")
}

// DetectionStatus returns a UI-friendly status label from sidecar.
func DetectionStatus(s *Sidecar) string {
	if s == nil {
		return StatePending
	}
	switch s.State {
	case StateFailed:
		return StateFailed
	case StateSkipped:
		return StateSkipped
	case StateSuccess:
		if s.HasPerson || s.HasAnimal || s.HasVehicle {
			return "detected"
		}
		return "none"
	case StatePending:
		return StatePending
	default:
		return StatePending
	}
}
